<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{this['Name']}}</title>
<link href="//fonts.googleapis.com/css?family=Montserrat:300,400|Open+Sans:300,300i,400,400i" rel="stylesheet">
<link media="all" rel="stylesheet" href="/css/main.css">
<link media="all" rel="stylesheet" href="/css/dev.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.js"></script>
<script src="/js/jquery.main.js"></script>
<script src="//use.fontawesome.com/f9ac8cd83a.js"></script>